In [1]:
from keras.datasets import mnist

Using TensorFlow backend.


In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [7]:
test_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [8]:
from keras import models
from keras import layers

In [9]:
network = models.sequential()
network.add(layers.Dense(512, activation = 'relu'), input_shape=(28 * 28,))
network.add(layers.Dense(10, activation = 'softmax'))

AttributeError: module 'keras.models' has no attribute 'sequential'

In [10]:
network = models.Sequential()
network.add(layers.Dense(512, activation = 'relu'), input_shape=(28 * 28,))
network.add(layers.Dense(10, activation = 'softmax'))

TypeError: add() got an unexpected keyword argument 'input_shape'

In [11]:
network = models.sequential()
network.add(layers.Dense(512, activation = 'relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation = 'softmax'))

AttributeError: module 'keras.models' has no attribute 'sequential'

In [12]:
network = models.Sequential()
network.add(layers.Dense(512, activation = 'relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation = 'softmax'))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [13]:
network.compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [14]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float') / 255

In [15]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [16]:
network.fit(train_images, train_labels, epochs = 5, batch_size = 128)


Epoch 1/5
60000/60000 [==============================] - 2s 27us/step - loss: 0.2576 - accuracy: 0.9245
Epoch 2/5
60000/60000 [==============================] - 2s 27us/step - loss: 0.1032 - accuracy: 0.9689
Epoch 3/5
60000/60000 [==============================] - 1s 25us/step - loss: 0.0681 - accuracy: 0.9797
Epoch 4/5
60000/60000 [==============================] - 1s 24us/step - loss: 0.0501 - accuracy: 0.9849
Epoch 5/5
60000/60000 [==============================] - 1s 24us/step - loss: 0.0382 - accuracy: 0.9883


In [17]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 0s 25us/step
test_acc: 0.9794999957084656


In [18]:
import numpy as np

In [19]:
x = np.array(12)
x

array(12)

In [20]:
x.ndim

0

In [21]:
x = np.array([12, 3, 6, 14])
x

array([12,  3,  6, 14])

In [22]:
x.ndim

1

In [23]:
x = np.array([
    [5, 78, 2, 34, 0],
    [6, 79, 3, 35, 1],
    [7, 80, 4, 36, 2]
])
x.ndim

2

In [24]:
x = np.array([
    [
        [5, 78, 2, 34, 0],
        [6, 78, 3, 35, 1],
        [7, 80, 4, 36, 2]
    ],
    [
        [5, 78, 2, 34, 0],
        [6, 78, 3, 35, 1],
        [7, 80, 4, 36, 2]
    ],
    [
        [5, 78, 2, 34, 0],
        [6, 78, 3, 35, 1],
        [7, 80, 4, 36, 2]
    ]
])
x.ndim

3

In [25]:
print(train_images.ndim)

2


In [26]:
print(train_images.shape)

(60000, 784)
